apiVersion: v1
kind: Pod
metadata:
  name: memory-stress
  namespace: ai-lab

spec:
  containers:
  - name: memory-stress
    image: polinux/stress

    resources:
      limits:
        memory: "50Mi"

    command:
    - stress

    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "100M"
    - "--vm-hang"
    - "1"